package controller;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import koneksi.Koneksi;
import model.AuditLog;
import model.Pengaturan;
import model.User;

public class PengaturanController {
    public Pengaturan getPengaturan(){ String sql="SELECT * FROM pengaturan ORDER BY id LIMIT 1"; try{ Connection c=Koneksi.getConnection(); if(c==null)return defaultSetting(); try(PreparedStatement ps=c.prepareStatement(sql); ResultSet rs=ps.executeQuery()){ if(rs.next()) return new Pengaturan(rs.getInt("id"),rs.getString("nama_sekolah"),rs.getString("alamat"),rs.getString("telepon"),rs.getString("email"),rs.getString("kepala_sekolah"),rs.getString("bendahara"),rs.getString("logo_path")); } } catch(SQLException ex){ System.err.println("pengaturan: "+ex.getMessage()); } return defaultSetting(); }
    private Pengaturan defaultSetting(){ return new Pengaturan(0,"SKM - Sistem Keuangan Madrasah","Alamat Madrasah","","","Kepala Sekolah","Bendahara",""); }
    public boolean savePengaturan(Pengaturan p){ String sql=p.getId()==0?"INSERT INTO pengaturan(nama_sekolah,alamat,telepon,email,kepala_sekolah,bendahara,logo_path) VALUES(?,?,?,?,?,?,?)":"UPDATE pengaturan SET nama_sekolah=?,alamat=?,telepon=?,email=?,kepala_sekolah=?,bendahara=?,logo_path=? WHERE id=?"; try{ Connection c=Koneksi.getConnection(); if(c==null)return false; try(PreparedStatement ps=c.prepareStatement(sql)){ ps.setString(1,p.getNamaSekolah()); ps.setString(2,p.getAlamat()); ps.setString(3,p.getTelepon()); ps.setString(4,p.getEmail()); ps.setString(5,p.getKepalaSekolah()); ps.setString(6,p.getBendahara()); ps.setString(7,p.getLogoPath()); if(p.getId()>0)ps.setInt(8,p.getId()); boolean ok=ps.executeUpdate()>0; if(ok) AuditLogger.log("UPDATE","pengaturan","",p.getNamaSekolah()); return ok; } } catch(SQLException ex){ System.err.println("save pengaturan: "+ex.getMessage()); return false; } }
    public List<User> getAllUsers(){ List<User> list=new ArrayList<>(); try{ Connection c=Koneksi.getConnection(); if(c==null)return list; try(PreparedStatement ps=c.prepareStatement("SELECT id,nama,username,password,role FROM users ORDER BY nama"); ResultSet rs=ps.executeQuery()){ while(rs.next()) list.add(new User(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5))); } } catch(SQLException ex){ System.err.println("users: "+ex.getMessage()); } return list; }
    public boolean saveUser(User u){ String sql=u.getId()==0?"INSERT INTO users(nama,username,password,role) VALUES(?,?,?,?)":"UPDATE users SET nama=?,username=?,role=? WHERE id=?"; try{ Connection c=Koneksi.getConnection(); if(c==null)return false; try(PreparedStatement ps=c.prepareStatement(sql)){ ps.setString(1,u.getNama()); ps.setString(2,u.getUsername()); if(u.getId()==0){ ps.setString(3,AuthController.hashPassword(u.getPassword())); ps.setString(4,u.getRole()); } else { ps.setString(3,u.getRole()); ps.setInt(4,u.getId()); } boolean ok=ps.executeUpdate()>0; if(ok) AuditLogger.log(u.getId()==0?"INSERT":"UPDATE","users","",u.getUsername()); return ok; } } catch(SQLException ex){ System.err.println("save user: "+ex.getMessage()); return false; } }
    public boolean deleteUser(int id){ try{ Connection c=Koneksi.getConnection(); if(c==null)return false; try(PreparedStatement ps=c.prepareStatement("DELETE FROM users WHERE id=?")){ ps.setInt(1,id); boolean ok=ps.executeUpdate()>0; if(ok) AuditLogger.log("DELETE","users",String.valueOf(id),""); return ok; } } catch(SQLException ex){ System.err.println("delete user: "+ex.getMessage()); return false; } }
    public boolean gantiPassword(int userId,String passwordBaru){ try{ Connection c=Koneksi.getConnection(); if(c==null)return false; try(PreparedStatement ps=c.prepareStatement("UPDATE users SET password=? WHERE id=?")){ ps.setString(1,AuthController.hashPassword(passwordBaru)); ps.setInt(2,userId); boolean ok=ps.executeUpdate()>0; if(ok) AuditLogger.log("PASSWORD","users",String.valueOf(userId),"diganti"); return ok; } } catch(SQLException ex){ System.err.println("password: "+ex.getMessage()); return false; } }
    public List<AuditLog> getAuditLog(){ List<AuditLog> list=new ArrayList<>(); String sql="SELECT a.*,u.nama nama_user FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.waktu DESC LIMIT 500"; try{ Connection c=Koneksi.getConnection(); if(c==null)return list; try(PreparedStatement ps=c.prepareStatement(sql); ResultSet rs=ps.executeQuery()){ while(rs.next()) list.add(new AuditLog(rs.getInt("id"),rs.getInt("user_id"),rs.getString("nama_user"),rs.getString("aksi"),rs.getString("tabel_target"),rs.getString("data_lama"),rs.getString("data_baru"),rs.getTimestamp("waktu").toLocalDateTime())); } } catch(SQLException ex){ System.err.println("audit: "+ex.getMessage()); } return list; }
}
