package form;

import controller.PengaturanController;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.AuditLog;
import model.Pengaturan;
import model.User;
import util.UIUtils;

public class PengaturanForm extends JPanel { private final PengaturanController c=new PengaturanController(); private final DefaultTableModel userModel=new DefaultTableModel(new String[]{"ID","Nama","Username","Role"},0); private final DefaultTableModel auditModel=new DefaultTableModel(new String[]{"Waktu","User","Aksi","Tabel","Data Lama","Data Baru"},0); public PengaturanForm(){ setLayout(new BorderLayout()); JPanel p=UIUtils.page("Pengaturan"); JTabbedPane tabs=new JTabbedPane(); tabs.addTab("Profil Sekolah",profil()); tabs.addTab("Manajemen User",users()); tabs.addTab("Audit Log",audit()); p.add(tabs); add(p); }
private JPanel profil(){ Pengaturan pg=c.getPengaturan(); JPanel p=UIUtils.card(); p.setLayout(new BorderLayout()); JPanel f=new JPanel(new GridLayout(0,2,8,8)); f.setOpaque(false); JTextField nama=UIUtils.textField(24), alamat=UIUtils.textField(24), telp=UIUtils.textField(16), email=UIUtils.textField(18), kep=UIUtils.textField(20), ben=UIUtils.textField(20), logo=UIUtils.textField(24); nama.setText(pg.getNamaSekolah()); alamat.setText(pg.getAlamat()); telp.setText(pg.getTelepon()); email.setText(pg.getEmail()); kep.setText(pg.getKepalaSekolah()); ben.setText(pg.getBendahara()); logo.setText(pg.getLogoPath()); f.add(UIUtils.formLabel("Nama Sekolah"));f.add(nama); f.add(UIUtils.formLabel("Alamat"));f.add(alamat); f.add(UIUtils.formLabel("Telepon"));f.add(telp); f.add(UIUtils.formLabel("Email"));f.add(email); f.add(UIUtils.formLabel("Kepala Sekolah"));f.add(kep); f.add(UIUtils.formLabel("Bendahara"));f.add(ben); JButton choose=UIUtils.buttonOutline("Upload Logo",UIUtils.BLUE); choose.addActionListener(e->{JFileChooser fc=new JFileChooser(); if(fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)logo.setText(fc.getSelectedFile().getAbsolutePath());}); f.add(choose); f.add(logo); JButton save=UIUtils.button("SIMPAN",UIUtils.GREEN); save.addActionListener(e->{Pengaturan val=new Pengaturan(pg.getId(),nama.getText(),alamat.getText(),telp.getText(),email.getText(),kep.getText(),ben.getText(),logo.getText()); if(c.savePengaturan(val))UIUtils.showSuccess(this,"Tersimpan"); else UIUtils.showError(this,"Gagal");}); p.add(f); p.add(save,BorderLayout.SOUTH); p.add(UIUtils.schoolLogo(120),BorderLayout.EAST); return p; }
private JPanel users(){ JPanel p=new JPanel(new BorderLayout(0,10)); p.setOpaque(false); JTable table=new JTable(userModel); table.removeColumn(table.getColumnModel().getColumn(0)); JButton add=UIUtils.button("TAMBAH USER",UIUtils.GREEN), del=UIUtils.button("HAPUS",UIUtils.RED), pass=UIUtils.button("GANTI PASSWORD",UIUtils.BLUE); p.add(UIUtils.toolbar(add,del,pass),BorderLayout.NORTH); p.add(UIUtils.tableScroll(table)); Runnable load=()->{userModel.setRowCount(0); for(User u:c.getAllUsers())userModel.addRow(new Object[]{u.getId(),u.getNama(),u.getUsername(),u.getRole()});}; add.addActionListener(e->{JTextField n=UIUtils.textField(18),u=UIUtils.textField(18); JPasswordField pw=UIUtils.passwordField(18); JComboBox<String> role=new JComboBox<>(new String[]{"ADMIN","KASIR"}); JPanel d=new JPanel(new GridLayout(0,1)); d.add(UIUtils.formLabel("Nama"));d.add(n);d.add(UIUtils.formLabel("Username"));d.add(u);d.add(UIUtils.formLabel("Password"));d.add(pw);d.add(UIUtils.formLabel("Role"));d.add(role); if(JOptionPane.showConfirmDialog(this,d,"Tambah User",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){c.saveUser(new User(0,n.getText(),u.getText(),new String(pw.getPassword()),String.valueOf(role.getSelectedItem()))); load.run();}}); del.addActionListener(e->{int r=table.getSelectedRow(); if(r>=0)c.deleteUser((int)userModel.getValueAt(table.convertRowIndexToModel(r),0)); load.run();}); pass.addActionListener(e->{int r=table.getSelectedRow(); if(r>=0){String pw=JOptionPane.showInputDialog(this,"Password baru"); if(pw!=null)c.gantiPassword((int)userModel.getValueAt(table.convertRowIndexToModel(r),0),pw);}}); load.run(); return p; }
private JPanel audit(){ JPanel p=new JPanel(new BorderLayout(0,10)); p.setOpaque(false); JTextField search=UIUtils.textField(24); JTable table=new JTable(auditModel); TableRowSorter<DefaultTableModel> sorter=new TableRowSorter<>(auditModel); table.setRowSorter(sorter); UIUtils.bindSearch(search,sorter); p.add(UIUtils.toolbar(UIUtils.formLabel("Cari"),search),BorderLayout.NORTH); p.add(UIUtils.tableScroll(table)); auditModel.setRowCount(0); for(AuditLog a:c.getAuditLog())auditModel.addRow(new Object[]{a.getWaktu(),a.getNamaUser(),a.getAksi(),a.getTabelTarget(),a.getDataLama(),a.getDataBaru()}); return p; }
}
